### ISSUE TITLE
Prevent the package from being upgraded

### ISSUE THREAD

**Issue by nkakouros** [apolloclark/ansible-role-packetbeat#1]
As I understand it, the beats suite gets updated quite frequently with even minor versions introducing breaking changes that require new config templates in this role. 

If this is the case, the role should hold the packetbeat/auditbeat package from being updated. The reason is that it happens that the version in the repos is newer that the one selected by the user (or the newest one supported by this role). Thus, if before the role runs, an `apt` task is run that updates the system generally, then, when the role runs, the installation task will fail due to the package being downgraded:

```
[02:53:20] apolloclark.auditbeat : Install from repo (if choosing the 5.6.x or 6.x version) | blueprint-dns | FAILED | 3589ms
{
  - stdout: Reading package lists...
            Building dependency tree...
            Reading state information...
            The following package was automatically installed and is no longer required:
              grub-pc-bin
            Use 'sudo apt autoremove' to remove it.
            The following packages will be DOWNGRADED:
              auditbeat
            0 upgraded, 0 newly installed, 1 downgraded, 0 to remove and 1 not upgraded.
  - rc: 100
  - stderr: E: Packages were downgraded and -y was used without --allow-downgrades.
  - msg: '/usr/bin/apt-get -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold"      install 'auditbeat=6.5.4'' failed: E: Packages were downgraded and -y was used without --allow-downgrades.
  - cache_updated: False
  - cache_update_time: 1550541200
  - warnings: [ Could not find aptitude. Using apt-get instead ]
  - stderr_lines: [ E: Packages were downgraded and -y was used without --allow-downgrades. ]
  - changed: False
}
```

**Comment by apolloclark** [comment]
I work as a security engineer. All packages should be upgraded on all systems every 7 days; that is the purpose of all of my repos.

**Comment by nkakouros** [comment]
But how do you handle packetbeat upgrades? Doesn't the system update upgrade packetbeat to a newer version that the role can support? What happens to idempotency then? And how do you deal with the role failing in this case as I showed you above?

**Comment by nkakouros** [comment]
In case my original comment was not clear enough, the following procedure results in **failure**:

- install packetbeat with role
- update system, including packetbeat to eg version 6.6.0 (as it happens now)
- rerun the role
--> :boom: FAILURE :boom:
